In [36]:
#Q1
import numpy as np
array1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
print(array1)
array2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(array2)
print("Distinct items between two arrays:")
print(np.intersect1d(array1, array2))
print("unique common values between two arrays:")
print(np.intersect1d(array1, array2))

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
Distinct items between two arrays:
[2 4]
unique common values between two arrays:
[2 4]


In [7]:
#Q2
arr = np.array([[1.,6.,11.],[2.,7.,12.],[3.,8.,13.],[4.,9.,14.],[5.,10.,15.]])
arr

array([[ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.],
       [ 5., 10., 15.]])

In [4]:
#Q3
import numpy as np
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

np.setdiff1d(a,b)

array([ 1,  7,  8, 15])

In [34]:
#Q4
# The distance from New York City to Key West, Florida is 1522 miles
# 1522-120=1402   31days-2days=29days
 np.random.randint(10,size=10)

IndentationError: unexpected indent (<ipython-input-34-9f1596b10bc3>, line 4)

In [7]:
#Q5
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [8]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [12]:
# get the NYC consumption of water in millions of gallons per day
# get the third column of nyc_water
nyc_consumption=nyc_water[:, 2]
print(nyc_consumption)

[1512.  1506.  1309.  1382.  1424.  1465.  1326.  1351.  1447.  1484.
 1402.  1424.  1469.  1369.  1368.5 1357.7 1325.7 1297.9 1205.5 1219.5
 1237.2 1240.4 1184.  1135.6 1093.7 1099.5 1138.  1069.  1114.  1098.
 1007.5 1039.  1021.  1009.1 1006.1  996.  1009.  1002.   990.2]


In [18]:
# What is the maximum yearly NYC consumption of water in millions of gallons per day?
max(nyc_consumption)

1512.0

In [15]:
year=nyc_water[:, 0]
print(year)

[1979. 1980. 1981. 1982. 1983. 1984. 1985. 1986. 1987. 1988. 1989. 1990.
 1991. 1992. 1993. 1994. 1995. 1996. 1997. 1998. 1999. 2000. 2001. 2002.
 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010. 2011. 2012. 2013. 2014.
 2015. 2016. 2017.]


In [16]:
# How many calendar years are represented within this data set? 
year.shape

(39,)

In [19]:
capita_daily_consumption=nyc_water[:, 3]
print(capita_daily_consumption)

[213. 213. 185. 194. 198. 203. 182. 185. 197. 202. 191. 194. 199. 184.
 182. 179. 174. 169. 155. 155. 156. 155. 148. 141. 136. 136. 141. 132.
 137. 135. 123. 127. 123. 121. 119. 118. 118. 117. 115.]


In [21]:
# What is the mean and the standard deviation of the per capita daily water consumption?
mean, sd=np.mean(capita_daily_consumption), np.std(capita_daily_consumption)
print(mean, sd)

160.30769230769232 31.51894330370624


In [23]:
pop=nyc_water[:, 1]
print(pop)

[7102100.  7071639.  7089241.  7109105.  7181224.  7234514.  7274054.
 7319246.  7342476.  7353719.  7344175.  7335650.  7374501.  7428944.
 7506166.  7570458.  7633040.  7697812.  7773443.  7858259.  7947660.
 8008278.  8024963.5 8041649.  8058334.5 8075020.  8091705.5 8108391.
 8125076.5 8141762.  8158447.5 8175133.  8284098.  8361179.  8422460.
 8471990.  8516502.  8537673.  8622698. ]


In [25]:
#What is the increase or decrease in population from year to year?
pop_diff=np.diff(pop)
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
